spring:
  cloud:
    gateway:
      x-forwarded: true
      routes:
        - id: green
          uri: http://localhost:8070
          predicates:
            - Path=/api/**
            - Header=x-env, g
#          filters:
#            - PrefixPath=/green
        - id: blue
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
#          - id: test
#            uri: http://localhost:8090
#            predicates:
#              - Path=/api/**
#            filters:
#              - AddRequestHeader=Test, 1234
#          - id: blue
#            uri: http://blue.localhost:8090
#            predicates:
#              - Host=blue.localhost:**
#              - Path=/api/**
#          - id: green
#            uri: http://green.localhost:8090
#            predicates:
#              - Host=green.**
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    org.springframework.boot.autoconfigure.web: debug
    reactor.netty: debug
    redisratelimiter: debug
    com:
      leel2415:
        springcloudgateway: debug

management:
  endpoint:
    gateway:
      enabled: true # default value

  endpoints:
    web:
      exposure:
        include: gateway
